### ISSUE TITLE
gkTabsItem

### ISSUE THREAD

**Issue by Janekkk333** [GavickPro/GK-Tabs#9]
If I do not select the default tab in backend, so the frontend side shows only the inactive tabs menu. TabsItems are hide. When I click on any tab in this menu, it continues to open a tabs item content.
And now for what I need to know.
When I click a second time on the same tab in tabnav, I need that opened tabitem close again. This means that the appearance on the page will again only the inactive tabs menu.
Could you advise me on how to achieve this? Because currently it does not work. When I have had it opened tabsitem second click closes. Tabsitem is still open.

**Comment by piotrkunicki** [comment]
Hello,
Could yo please provide your site URL with the GK tabs widget activated? Then I'll be able to analyze it.

**Comment by Janekkk333** [comment]
Ok.

streeter.cz

login:
UN: Lukasino
P: 123123123


2015-03-09 11:54 GMT+01:00 Piotr Kunicki <notifications@github.com>:

**Comment by piotrkunicki** [comment]
I've edited your comment (it's public repository, so please don't send sensitive data like username/passwords), you can send it via email. (you can find the address on the github profile page)

Unfortunately this repository is dedicated for WordPress version of GK Tabs, for Joomla users the repository is here:
https://github.com/GavickPro/Tabs-GK5

Please create new issue there.
